export const PERM_ADMIN = 'administrate_lobby'
export const PERM_SETUP = 'setup'
export const PERM_GAMERULE = 'gamerules'
export const PERM_CHANNELS = 'channels'
export const PERM_PERMISSIONS = 'permissions'
export const PERM_LISTING = 'listing'
